//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalkingKeyboard.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TalkingKeyboard.Infrastructure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de
        ///la
        ///que
        ///el
        ///en
        ///los
        ///se
        ///del
        ///las
        ///un
        ///por
        ///con
        ///no
        ///una
        ///su
        ///para
        ///es
        ///al
        ///lo
        ///como
        ///más
        ///pero
        ///sus
        ///le
        ///ha
        ///me
        ///si
        ///sin
        ///sobre
        ///este
        ///ya
        ///entre
        ///cuando
        ///todo
        ///esta
        ///ser
        ///son
        ///dos
        ///también
        ///fue
        ///había
        ///era
        ///muy
        ///años
        ///hasta
        ///desde
        ///está
        ///mi
        ///porque
        ///qué
        ///sólo
        ///han
        ///yo
        ///hay
        ///vez
        ///puede
        ///todos
        ///así
        ///nos
        ///ni
        ///parte
        ///tiene
        ///él
        ///uno
        ///donde
        ///bien
        ///tiempo
        ///mismo
        ///ese
        ///ahora
        ///cada
        ///vida
        ///otro
        ///después
        ///te
        ///otros
        ///aunque
        ///esa
        ///eso
        ///hace
        ///otra
        ///gobierno
        ///tan
        ///durante
        ///siempre
        ///día
        ///tanto
        ///ella
        ///tres
        ///sí
        ///dijo
        ///sido
        ///gran
        ///país
        ///según
        ///menos
        ///mundo
        ///año
        ///antes
        ///estado
        ///contra
        ///sino
        ///forma
        ///caso
        ///nada
        ///hacer
        ///general [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpanishSpain {
            get {
                return ResourceManager.GetString("SpanishSpain", resourceCulture);
            }
        }
    }
}
